"""Add project export jobs

Revision ID: 9e0662b10ec7
Revises: 9f90c08d757b
Create Date: 2026-04-21 08:26:39.646028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e0662b10ec7'
down_revision: Union[str, None] = '9f90c08d757b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voices',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('model_url', sa.String(), nullable=True),
    sa.Column('config_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_export_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('export_format', sa.String(length=32), nullable=False),
    sa.Column('gap_seconds', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='processing', nullable=False),
    sa.Column('progress', sa.Integer(), server_default='0', nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('output_data', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_export_jobs_project_id'), 'project_export_jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_export_jobs_status'), 'project_export_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_project_export_jobs_user_id'), 'project_export_jobs', ['user_id'], unique=False)
    op.create_table('scenes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scene_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('voice_id', sa.String(length=50), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('audio_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_request_logs_id', table_name='request_logs')
    op.drop_index('ix_request_logs_path', table_name='request_logs')
    op.drop_index('ix_request_logs_timestamp', table_name='request_logs')
    op.drop_index('ix_request_logs_user_id', table_name='request_logs')
    op.drop_table('request_logs')
    op.drop_index('ix_usage_snapshot_user_feature_date', table_name='usage_snapshots')
    op.drop_index('ix_usage_snapshots_date', table_name='usage_snapshots')
    op.drop_index('ix_usage_snapshots_id', table_name='usage_snapshots')
    op.drop_index('ix_usage_snapshots_user_id', table_name='usage_snapshots')
    op.drop_table('usage_snapshots')
    op.add_column('api_keys', sa.Column('rate_limit_window', sa.Integer(), nullable=False))
    op.add_column('api_keys', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('api_keys', sa.Column('scopes', sa.String(length=255), nullable=False))
    op.add_column('api_keys', sa.Column('total_requests', sa.Integer(), nullable=False))
    op.add_column('api_keys', sa.Column('failed_requests', sa.Integer(), nullable=False))
    op.alter_column('api_keys', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('api_keys', 'rate_limit',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('api_keys', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('api_keys_user_id_fkey', 'api_keys', type_='foreignkey')
    op.create_foreign_key(None, 'api_keys', 'users', ['user_id'], ['id'])
    op.alter_column('usage_history', 'characters_used',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('usage_history', 'api_calls',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('usage_history', 'storage_mb',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_quotas', 'tier',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'free'::character varying"))
    op.alter_column('user_quotas', 'characters_used',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_quotas', 'characters_limit',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('5000'))
    op.alter_column('user_quotas', 'storage_used_mb',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_quotas', 'storage_limit_mb',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('user_quotas', 'api_calls_today',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('user_quotas', 'api_calls_limit',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('100'))
    op.alter_column('user_quotas', 'last_reset_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_quotas', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_quotas', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_user_quotas_user_id', table_name='user_quotas')
    op.alter_column('users', 'subscription_tier',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'free'::character varying"))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'subscription_tier',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'free'::character varying"))
    op.create_index('ix_user_quotas_user_id', 'user_quotas', ['user_id'], unique=True)
    op.alter_column('user_quotas', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_quotas', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_quotas', 'last_reset_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_quotas', 'api_calls_limit',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('100'))
    op.alter_column('user_quotas', 'api_calls_today',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user_quotas', 'storage_limit_mb',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('100'))
    op.alter_column('user_quotas', 'storage_used_mb',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user_quotas', 'characters_limit',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('5000'))
    op.alter_column('user_quotas', 'characters_used',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user_quotas', 'tier',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'free'::character varying"))
    op.alter_column('usage_history', 'storage_mb',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('usage_history', 'api_calls',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('usage_history', 'characters_used',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.create_foreign_key('api_keys_user_id_fkey', 'api_keys', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('api_keys', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('api_keys', 'rate_limit',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('100'))
    op.alter_column('api_keys', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('api_keys', 'failed_requests')
    op.drop_column('api_keys', 'total_requests')
    op.drop_column('api_keys', 'scopes')
    op.drop_column('api_keys', 'expires_at')
    op.drop_column('api_keys', 'rate_limit_window')
    op.create_table('usage_snapshots',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('feature', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('characters_used', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('api_calls', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='usage_snapshots_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='usage_snapshots_pkey')
    )
    op.create_index('ix_usage_snapshots_user_id', 'usage_snapshots', ['user_id'], unique=False)
    op.create_index('ix_usage_snapshots_id', 'usage_snapshots', ['id'], unique=False)
    op.create_index('ix_usage_snapshots_date', 'usage_snapshots', ['date'], unique=False)
    op.create_index('ix_usage_snapshot_user_feature_date', 'usage_snapshots', ['user_id', 'feature', 'date'], unique=True)
    op.create_table('request_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('method', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('latency_ms', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='request_logs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='request_logs_pkey')
    )
    op.create_index('ix_request_logs_user_id', 'request_logs', ['user_id'], unique=False)
    op.create_index('ix_request_logs_timestamp', 'request_logs', ['timestamp'], unique=False)
    op.create_index('ix_request_logs_path', 'request_logs', ['path'], unique=False)
    op.create_index('ix_request_logs_id', 'request_logs', ['id'], unique=False)
    op.drop_table('segments')
    op.drop_table('scenes')
    op.drop_index(op.f('ix_project_export_jobs_user_id'), table_name='project_export_jobs')
    op.drop_index(op.f('ix_project_export_jobs_status'), table_name='project_export_jobs')
    op.drop_index(op.f('ix_project_export_jobs_project_id'), table_name='project_export_jobs')
    op.drop_table('project_export_jobs')
    op.drop_table('projects')
    op.drop_table('voices')
    # ### end Alembic commands ###
